CREATE TABLE IF NOT EXISTS coordinator_templates (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES coordinator_users(id),
    template_name TEXT NOT NULL,
    template_subject TEXT NOT NULL,
    template_content TEXT NOT NULL
);