CREATE TABLE IF NOT EXISTS coordinator_pms (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES coordinator_users(id),
    pm_name TEXT NOT NULL,
    pm_email TEXT NOT NULL 
);