DROP TYPE IF EXISTS status CASCADE;
CREATE TYPE status AS ENUM (
    'none',
    'reached',
    'completed'
);

CREATE TABLE IF NOT EXISTS coordinator_list_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES coordinator_users(id),
    status status NOT NULL,
    project TEXT NOT NULL,
    project_url TEXT DEFAULT NULL,
    contact TEXT NOT NULL,
    contact_url TEXT DEFAULT NULL,
    pm_id INTEGER REFERENCES coordinator_pms(id) ON DELETE CASCADE,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_completed TIMESTAMP DEFAULT NULL,
    notes TEXT
);